### ISSUE TITLE
Bug: texture tiles not rendered if setup by state machine

### ISSUE THREAD

**Issue by michalmoc** [443eb9/bevy_entitiles#14] opened 2024-02-05 20:26 UTC
**Description**

I've tried to run example 'basic.rs', but setup is called via `.add_systems(OnEnter(AppState::Other), setup)`. Colour tilemap is displayed correctly, but square and isometric textures are not rendered at all. If running as `.add_systems(Startup, setup)` everything works correctly.

**Reproduction**
Run code (function `setup()` is copied directly from the example)

```rust
use bevy::diagnostic::LogDiagnosticsPlugin;
use bevy::log::LogPlugin;
use bevy::prelude::*;
use bevy::render::render_resource::FilterMode;
use bevy::window::PresentMode;
use bevy_entitiles::prelude::{
    PureColorTilemapBundle, TileArea, TileBuilder, TileLayer, TileRenderSize, TileUpdater,
    TilemapBundle, TilemapName, TilemapSlotSize, TilemapStorage, TilemapTexture,
    TilemapTextureDescriptor, TilemapTransform, TilemapType,
};
use bevy_entitiles::tilemap::map::TilemapRotation;
use bevy_entitiles::tilemap::tile::{LayerUpdater, TileFlip, TileLayerPosition};
use bevy_entitiles::EntiTilesPlugin;

#[derive(States, PartialEq, Eq, Debug, Clone, Hash, Default, Copy)]
pub enum AppState {
    #[default]
    Init,
    Other,
}

fn main() {
    App::new()
        .add_plugins(
            DefaultPlugins
                .set(WindowPlugin {
                    primary_window: Some(Window {
                        title: String::from("Tilemap example"),
                        resolution: (1820., 920.).into(),
                        // disable vsync so we can see the raw FPS speed
                        present_mode: PresentMode::Immediate,
                        ..default()
                    }),
                    ..default()
                })
                .set(LogPlugin {
                    filter: "info,rpg=debug".to_string(),
                    level: bevy::log::Level::DEBUG,
                }),
        )
        .add_state::<AppState>()
        .add_plugins(LogDiagnosticsPlugin::default())
        .add_plugins(EntiTilesPlugin)
        .add_systems(OnEnter(AppState::Other), setup)
        .add_systems(Update, change_state.run_if(in_state(AppState::Init)))
        .run();
}

fn change_state(mut app_state: ResMut<NextState<AppState>>) {
    app_state.set(AppState::Other);
}

fn setup(mut commands: Commands, assets_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());

    let entity = commands.spawn_empty().id();
    // You can go to each component's definition to see what they do.
    let mut tilemap = TilemapBundle {
        name: TilemapName("test_map".to_string()),
        tile_render_size: TileRenderSize(Vec2 { x: 16., y: 16. }),
        slot_size: TilemapSlotSize(Vec2 { x: 16., y: 16. }),
        ty: TilemapType::Square,
        storage: TilemapStorage::new(16, entity),
        texture: TilemapTexture::new(
            assets_server.load("test_square.png"),
            TilemapTextureDescriptor::new(
                UVec2 { x: 32, y: 32 },
                UVec2 { x: 16, y: 16 },
                FilterMode::Nearest,
            ),
            TilemapRotation::None,
        ),
        ..Default::default()
    };

    tilemap.storage.fill_rect(
        &mut commands,
        TileArea::new(IVec2::ZERO, UVec2 { x: 20, y: 10 }),
        TileBuilder::new().with_layer(0, TileLayer::new().with_texture_index(0)),
    );

    tilemap.storage.fill_rect(
        &mut commands,
        TileArea::new(IVec2 { x: 2, y: 2 }, UVec2 { x: 10, y: 7 }),
        TileBuilder::new()
            .with_layer(0, TileLayer::new().with_texture_index(1))
            .with_color(Vec4::new(0.8, 1., 0.8, 0.5)),
    );

    tilemap.storage.set(
        &mut commands,
        IVec2 { x: 18, y: 8 },
        TileBuilder::new()
            .with_layer(0, TileLayer::new().with_texture_index(0))
            .with_color(Color::BLUE.into()),
    );

    tilemap.storage.set(
        &mut commands,
        IVec2 { x: 1, y: 1 },
        TileBuilder::new().with_layer(
            1,
            TileLayer::new()
                .with_texture_index(1)
                .with_flip(TileFlip::Horizontal),
        ),
    );

    tilemap.storage.set(
        &mut commands,
        IVec2 { x: 1, y: 2 },
        TileBuilder::new().with_layer(
            0,
            TileLayer::new()
                .with_texture_index(1)
                .with_flip(TileFlip::Vertical),
        ),
    );

    tilemap.storage.set(
        &mut commands,
        IVec2 { x: 1, y: 3 },
        TileBuilder::new().with_layer(
            0,
            TileLayer::new()
                .with_texture_index(1)
                .with_flip(TileFlip::Both),
        ),
    );

    tilemap.storage.update_rect(
        &mut commands,
        TileArea::new(IVec2 { x: 1, y: 3 }, UVec2 { x: 3, y: 3 }),
        TileUpdater {
            layer: Some(LayerUpdater {
                position: TileLayerPosition::Top,
                layer: TileLayer::new().with_texture_index(3),
            }),
            ..Default::default()
        },
    );

    commands.entity(entity).insert(tilemap);

    let entity = commands.spawn_empty().id();
    let mut tilemap = TilemapBundle {
        name: TilemapName("test_map".to_string()),
        tile_render_size: TileRenderSize(Vec2 { x: 32., y: 16. }),
        slot_size: TilemapSlotSize(Vec2 { x: 32., y: 16. }),
        ty: TilemapType::Isometric,
        storage: TilemapStorage::new(32, entity),
        texture: TilemapTexture::new(
            assets_server.load("test_isometric.png"),
            TilemapTextureDescriptor::new(
                UVec2 { x: 32, y: 32 },
                UVec2 { x: 32, y: 16 },
                FilterMode::Nearest,
            ),
            TilemapRotation::None,
        ),
        transform: TilemapTransform {
            translation: Vec2 { x: -400., y: 0. },
            ..Default::default()
        },
        ..Default::default()
    };

    tilemap.storage.fill_rect(
        &mut commands,
        TileArea::new(IVec2::ZERO, UVec2 { x: 20, y: 10 }),
        TileBuilder::new().with_layer(0, TileLayer::new().with_texture_index(0)),
    );

    commands.entity(entity).insert(tilemap);

    let entity = commands.spawn_empty().id();
    let mut tilemap = PureColorTilemapBundle {
        name: TilemapName("test_map".to_string()),
        tile_render_size: TileRenderSize(Vec2 { x: 16., y: 16. }),
        slot_size: TilemapSlotSize(Vec2 { x: 16., y: 16. }),
        ty: TilemapType::Square,
        storage: TilemapStorage::new(32, entity),
        transform: TilemapTransform {
            translation: Vec2 { x: 0., y: -300. },
            ..Default::default()
        },
        ..Default::default()
    };

    tilemap.storage.fill_rect(
        &mut commands,
        TileArea::new(IVec2::ZERO, UVec2 { x: 20, y: 10 }),
        TileBuilder::new()
            .with_layer(0, TileLayer::new().with_texture_index(0))
            .with_color(Vec4::new(1., 1., 0., 1.)),
    );

    commands.entity(entity).insert(tilemap);
}

```

**Screenshots**
![obraz](https://github.com/443eb9/bevy_entitiles/assets/13559018/2cdb7e4b-02df-4773-b296-506a692b824e)

**Versions**
 - OS: Linux
 - Crate and other dependencies: 
   - bevy = "0.12"
   - bevy_entitiles = "0.5.0"

**Additional**

**Comment by 443eb9** [comment] 2024-02-06 03:32
This is because the tilemap texture array cannot be created.

Once the texture is added to the tilemap, `entitiles` will try to fetch the image asset and change its usage. So the texture can be divided in to tiles later. But the problem is that, if it failed to get the image, it will simply `return` and does nothing...

This will be fixed in the next release.

**Comment by michalmoc** [comment] 2024-02-06 08:27
ok, preloading assets at startup fixes most of the problem, but there is still one part of the example missing:

![obraz](https://github.com/443eb9/bevy_entitiles/assets/13559018/f4d4d74f-841e-42a1-954a-c68541bd71f5)

code 
```rust
    tilemap.storage.update_rect(
        &mut commands,
        TileArea::new(IVec2 { x: 1, y: 3 }, UVec2 { x: 3, y: 3 }),
        TileUpdater {
            layer: Some(LayerUpdater {
                position: TileLayerPosition::Top,
                layer: TileLayer::new().with_texture_index(3),
            }),
            ..Default::default()
        },
    );
```
can be commented out with no consequences

**Comment by 443eb9** [comment] 2024-02-07 02:11
This currently can't work. What I edited above is the reason. Step 1 makes no sense, but it will cause the situation you mentioned. So sorry but you have to wait for the next release or the next merge to `master` branch.

**Comment by 443eb9** [comment] 2024-02-07 02:14
In fact, this issue is solved in `dev` branch. But the `dev` branch contains some incomplete code. If you really really need to solve it now, you can use the code in `dev` branch. As long as you use the default `StandrardTilemapMaterial`, it *might* be fine.

**Comment by 443eb9** [comment] 2024-02-07 03:27
Well, the good news is that I just completed the development for custom material and merged it to the master branch. So you can avoid this issue by using the master branch. You can even experience the new feature at the same time!

**Closed by 443eb9** 2024-02-07 03:27 UTC
Labels: bug, graphics
